import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LogoutButton from "./components/Logout/Logout";
import { isLoggedIn } from "./helpers/authHelper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="w-full text-center flex">
            <Link className="w-full text-center text-gray-400 font-bold text-2xl m-4 " href='/'>Cookunity FE Challenge</Link>
            {await isLoggedIn() && <div className="flex items-center mr-4"><LogoutButton /></div>}
          </div>
        </header>

        <main className="flex  min-h-screen justify-center m-auto items-start  p-4 gap-2 max-w-[1200px]">
          <div className="w-full h-full p-8 bg-gray-200 rounded-[16px]">{children}</div>
        </main>
      </body>
    </html >
  );
}
